#!/bin/bash
# Automated decompilation pipeline for NeXTSTEP ObjC binaries
# Usage: ./pipeline.sh <path-to-universal-binary-or-i386-slice>
set -e

BIN="$1"
if [ -z "$BIN" ]; then
    echo "Usage: $0 <path-to-universal-binary>"
    echo "  Decompiles all ObjC methods and produces compilable .m/.h files"
    exit 1
fi

# Find repo root (where this script lives)
REPO="$(cd "$(dirname "$0")" && pwd)"
GHIDRA="$REPO/ghidra"
SCRIPTS="$REPO/ghidra_scripts"
JAVA_HOME="/usr/lib/jvm/java-25-openjdk-amd64"
export JAVA_HOME

BIN="$(realpath "$BIN")"
DIR="$(dirname "$BIN")"
NAME="$(basename "$BIN")"
I386="$DIR/$NAME.i386"
OUTDIR="$DIR/analysis"
TMPDIR="/tmp/nextthunk_$$"
mkdir -p "$TMPDIR" "$OUTDIR"

cleanup() { rm -rf "$TMPDIR"; }
trap cleanup EXIT

echo "=== Pipeline: $NAME ==="
echo "  Repo:    $REPO"
echo "  Binary:  $BIN"
echo "  Output:  $OUTDIR"

# Step 1: Extract i386 slice or detect architecture
echo ""
echo "=== Step 1: Detect architecture ==="
ARCH="i386"
python3 -c "
import struct, shutil, os, sys
with open('$BIN', 'rb') as f:
    data = f.read()
magic_le = struct.unpack_from('<I', data, 0)[0]
magic_be = struct.unpack_from('>I', data, 0)[0]
if magic_be == 0xCAFEBABE:  # Universal/fat binary
    narchs = struct.unpack_from('>I', data, 4)[0]
    for i in range(narchs):
        off = 8 + i * 20
        cputype = struct.unpack_from('>I', data, off)[0]
        foff = struct.unpack_from('>I', data, off+8)[0]
        fsz = struct.unpack_from('>I', data, off+12)[0]
        if cputype == 7:  # CPU_TYPE_I386
            with open('$I386', 'wb') as out: out.write(data[foff:foff+fsz])
            print('I386')
            sys.exit(0)
        elif cputype == 18:  # CPU_TYPE_MC680x0
            with open('$I386', 'wb') as out: out.write(data[foff:foff+fsz])
            print('M68K')
            sys.exit(0)
    print('NONE')
    sys.exit(1)
elif magic_le == 0xFEEDFACE:  # i386 LE Mach-O
    shutil.copy('$BIN', '$I386')
    print('I386')
elif magic_be == 0xFEEDFACE:  # m68k BE Mach-O
    shutil.copy('$BIN', '$I386')
    print('M68K')
else:
    print(f'UNKNOWN (0x{magic_le:08x})')
    sys.exit(1)
" > "$TMPDIR/arch.txt"
ARCH=$(cat "$TMPDIR/arch.txt")
echo "  Architecture: $ARCH"

# Step 2: Dump ObjC metadata (method names + addresses)
echo ""
echo "=== Step 2: ObjC metadata ==="
python3 "$REPO/dump_objc_metadata.py" "$I386" "$OUTDIR"

# Build address list from metadata
grep -oP '0x[0-9a-fA-F]+\s+\[.*?\]' "$OUTDIR/objc_metadata.txt" | sed 's/\[//;s/\]//' > "$OUTDIR/addr_list.txt"
METHOD_COUNT=$(wc -l < "$OUTDIR/addr_list.txt")
echo "  $METHOD_COUNT methods"

# Step 3: Ghidra batch decompilation
echo ""
echo "=== Step 3: Ghidra decompilation ==="
if [ "$ARCH" = "M68K" ]; then
    GHIDRA_PROC="-processor 68000:BE:32:default"
else
    GHIDRA_PROC=""
fi
mkdir -p /tmp/ghidra_projects
rm -rf /tmp/ghidra_projects/${NAME}_decomp.* 2>/dev/null
"$GHIDRA/support/analyzeHeadless" /tmp/ghidra_projects "${NAME}_decomp" \
    -import "$I386" -overwrite -noanalysis \
    $GHIDRA_PROC \
    -scriptPath "$SCRIPTS" \
    -postScript DecompileBatch.java "$OUTDIR/addr_list.txt" > "$TMPDIR/raw_decompile.txt" 2>&1 || true

# Step 4: Extract class layout
echo ""
echo "=== Step 4: Class layout ==="
python3 "$REPO/dump_class_layout.py" "$I386" "$OUTDIR"

# Step 5: Build ObjC source files
echo ""
echo "=== Step 5: Build ObjC sources ==="
python3 "$REPO/build_sources.py" "$TMPDIR/raw_decompile.txt" "$TMPDIR" --app-name "$NAME" --class-info "$OUTDIR/class_info.json"

# Step 6: Resolve selectors (func_0xADDR -> objc_msgSend, PTR_s_* -> @selector())
echo ""
echo "=== Step 6: Resolve selectors ==="
python3 "$REPO/resolve_selectors.py" "$I386" "$TMPDIR/$NAME.m" > "$OUTDIR/$NAME.m" 2>/dev/null

# Step 7: Generate Info.plist
echo ""
echo "=== Step 7: App resources ==="
# Info.plist and makefile are generated in step 5
# Copy supporting files from tmpdir
cp "$TMPDIR/$NAME.h" "$OUTDIR/$NAME.h"
cp "$TMPDIR/${NAME}_stubs.m" "$OUTDIR/${NAME}_stubs.m"
cp "$TMPDIR/GNUmakefile" "$OUTDIR/GNUmakefile"
# Info.plist is generated by build_sources.py into tmpdir
cp "$TMPDIR/Info.plist" "$OUTDIR/Info.plist" 2>/dev/null || true
# Fix GNUmakefile to properly link GUI libraries
sed -i 's/ADDITIONAL_LDFLAGS/ADDITIONAL_TOOL_LIBS/' "$OUTDIR/GNUmakefile" 2>/dev/null || true
# Fix EnvelopeView superclass (decompiled as NSObject but it's a view subclass)
sed -i 's/@interface EnvelopeView : NSObject/@interface EnvelopeView : NSView/' "$OUTDIR/$NAME.h" "$OUTDIR/$NAME.m" 2>/dev/null || true
# Add AppKit import to .m file (needed now that EnvelopeView inherits NSView)
sed -i '1a #import <AppKit/AppKit.h>' "$OUTDIR/$NAME.m" 2>/dev/null || true

# Step 8: Build gmodels (runtime UI + nib preservation) + app bundle
echo ""
echo "=== Step 8: Build gmodels + app bundle ==="
# Pre-compile all tools if needed
. /usr/share/GNUstep/Makefiles/GNUstep.sh
for src in nib2gmodel.m gmodel2nib.m; do
    bin="$REPO/.${src%.m}.bin"
    [ -f "$bin" ] && continue
    echo "  Compiling $src..."
    gcc -o "$bin" "$REPO/$src" $(gnustep-config --objc-flags) -std=gnu99 -fpermissive \
        $(gnustep-config --base-libs) -lgnustep-gui 2>&1 | grep -v "warning" || true
done

# Generate Gorm-compatible .gmodel files
echo "  Converting nibs to Gorm gmodels..."
for nibdir in "$DIR" "$DIR/English.lproj"; do
    [ -d "$nibdir" ] || continue
    for nib in "$nibdir"/*.nib; do
        [ -f "$nib" ] || continue
        base=$(basename "$nib" .nib)
        cp "$nib" "$OUTDIR/"
        GMODEL="${nib%.nib}.gmodel"
        python3 "$REPO/nib2gmodel.py" "$nib"
        [ -f "$GMODEL" ] && cp "$GMODEL" "$OUTDIR/${base}.gmodel"
        # Fixup: create runtime-loadable version
        RUNTIME="$OUTDIR/${base}_runtime.gmodel"
        python3 "$REPO/fixup_gmodel.py" "$OUTDIR/${base}.gmodel"
    done
done

# Patch stubs to load _runtime.gmodel via NSBundle loadNibNamed:
STUBS="$OUTDIR/${NAME}_stubs.m"
if [ -f "$STUBS" ]; then
    python3 "$REPO/patch_stubs.py" "$STUBS" "$NAME" 2>&1 || echo "  Stub patching failed"
fi

# Build app bundle
mkdir -p "$OUTDIR/${NAME}.app/Resources"
cp "$OUTDIR/Info.plist" "$OUTDIR/${NAME}.app/Resources/" 2>/dev/null || true
for g in "$OUTDIR"/*.gmodel "$OUTDIR"/*_runtime.gmodel; do
    [ -f "$g" ] && cp "$g" "$OUTDIR/${NAME}.app/Resources/"
done
# Build the binary and copy into app bundle
(cd "$OUTDIR" && . /usr/share/GNUstep/Makefiles/GNUstep.sh && make -f GNUmakefile) 2>&1 | grep -E "^ |Linking|error" || true
BINARY=""
for p in "$OUTDIR/obj/$NAME" "$OUTDIR/$NAME"; do
    [ -f "$p" ] && BINARY="$p" && break
done
[ -n "$BINARY" ] && cp "$BINARY" "$OUTDIR/${NAME}.app/"
echo "  App bundle at $OUTDIR/${NAME}.app"
ls "$OUTDIR/${NAME}.app/Resources/" 2>/dev/null

echo ""
echo "=== Done! Output in $OUTDIR/ ==="
echo "  cd $OUTDIR && openapp ./${NAME}.app"
ls -la "$OUTDIR/$NAME.m" "$OUTDIR/$NAME.h" "$OUTDIR/${NAME}_stubs.m" "$OUTDIR/GNUmakefile" "$OUTDIR/Info.plist" 2>/dev/null
