include $(GNUSTEP_MAKEFILES)/common.make

TOOL_NAME = CreateAndArchive
CreateAndArchive_OBJC_FILES = create_and_archive.m
CreateAndArchive_OBJCFLAGS = -fobjc-exceptions -std=gnu99
CreateAndArchive_NEEDS_GUI = yes

include $(GNUSTEP_MAKEFILES)/tool.make
