include $(GNUSTEP_MAKEFILES)/common.make

TOOL_NAME = TestModel MakeModel
TestModel_OBJC_FILES = main.m
TestModel_OBJCFLAGS = -fobjc-exceptions -std=gnu99
TestModel_NEEDS_GUI = yes

MakeModel_OBJC_FILES = make_model.m
MakeModel_OBJCFLAGS = -fobjc-exceptions -std=gnu99
MakeModel_NEEDS_GUI = yes

include $(GNUSTEP_MAKEFILES)/tool.make
